#define WIN32_LEAN_AND_MEAN
#define _WINSOCKAPI_  // Prevent winsock.h from being included
#include <Windows.h>
#include <WinSock2.h>
#include "Logger.h"
#include "MapFix.h"
#include "LuaInterop.h"
#include "NetTune.h"
#include "SocketOptimizer.h"

namespace
{
    // A/B toggle: disable constant patching while validating SocketOptimizer-only behavior.
    constexpr bool kEnableNetTune = false;
}

// Forwarding all winmm.dll exports to the system version.
// Using System32 path because for 32-bit processes it's automatically 
// redirected to SysWOW64 on 64-bit Windows.
#pragma comment(linker, "/export:CloseDriver=C:\\Windows\\System32\\winmm.CloseDriver,@4")
#pragma comment(linker, "/export:DefDriverProc=C:\\Windows\\System32\\winmm.DefDriverProc,@5")
#pragma comment(linker, "/export:DriverCallback=C:\\Windows\\System32\\winmm.DriverCallback,@6")
#pragma comment(linker, "/export:DrvGetModuleHandle=C:\\Windows\\System32\\winmm.DrvGetModuleHandle,@7")
#pragma comment(linker, "/export:GetDriverModuleHandle=C:\\Windows\\System32\\winmm.GetDriverModuleHandle,@8")
#pragma comment(linker, "/export:NotifyCallbackData=C:\\Windows\\System32\\winmm.NotifyCallbackData,@9")
#pragma comment(linker, "/export:OpenDriver=C:\\Windows\\System32\\winmm.OpenDriver,@10")
#pragma comment(linker, "/export:PlaySound=C:\\Windows\\System32\\winmm.PlaySound,@11")
#pragma comment(linker, "/export:PlaySoundA=C:\\Windows\\System32\\winmm.PlaySoundA,@12")
#pragma comment(linker, "/export:PlaySoundW=C:\\Windows\\System32\\winmm.PlaySoundW,@13")
#pragma comment(linker, "/export:SendDriverMessage=C:\\Windows\\System32\\winmm.SendDriverMessage,@14")
#pragma comment(linker, "/export:WOW32DriverCallback=C:\\Windows\\System32\\winmm.WOW32DriverCallback,@15")
#pragma comment(linker, "/export:WOW32ResolveMultiMediaHandle=C:\\Windows\\System32\\winmm.WOW32ResolveMultiMediaHandle,@16")
#pragma comment(linker, "/export:WOWAppExit=C:\\Windows\\System32\\winmm.WOWAppExit,@17")
#pragma comment(linker, "/export:aux32Message=C:\\Windows\\System32\\winmm.aux32Message,@18")
#pragma comment(linker, "/export:auxGetDevCapsA=C:\\Windows\\System32\\winmm.auxGetDevCapsA,@19")
#pragma comment(linker, "/export:auxGetDevCapsW=C:\\Windows\\System32\\winmm.auxGetDevCapsW,@20")
#pragma comment(linker, "/export:auxGetNumDevs=C:\\Windows\\System32\\winmm.auxGetNumDevs,@21")
#pragma comment(linker, "/export:auxGetVolume=C:\\Windows\\System32\\winmm.auxGetVolume,@22")
#pragma comment(linker, "/export:auxOutMessage=C:\\Windows\\System32\\winmm.auxOutMessage,@23")
#pragma comment(linker, "/export:auxSetVolume=C:\\Windows\\System32\\winmm.auxSetVolume,@24")
#pragma comment(linker, "/export:joy32Message=C:\\Windows\\System32\\winmm.joy32Message,@25")
#pragma comment(linker, "/export:joyConfigChanged=C:\\Windows\\System32\\winmm.joyConfigChanged,@26")
#pragma comment(linker, "/export:joyGetDevCapsA=C:\\Windows\\System32\\winmm.joyGetDevCapsA,@27")
#pragma comment(linker, "/export:joyGetDevCapsW=C:\\Windows\\System32\\winmm.joyGetDevCapsW,@28")
#pragma comment(linker, "/export:joyGetNumDevs=C:\\Windows\\System32\\winmm.joyGetNumDevs,@29")
#pragma comment(linker, "/export:joyGetPos=C:\\Windows\\System32\\winmm.joyGetPos,@30")
#pragma comment(linker, "/export:joyGetPosEx=C:\\Windows\\System32\\winmm.joyGetPosEx,@31")
#pragma comment(linker, "/export:joyGetThreshold=C:\\Windows\\System32\\winmm.joyGetThreshold,@32")
#pragma comment(linker, "/export:joyReleaseCapture=C:\\Windows\\System32\\winmm.joyReleaseCapture,@33")
#pragma comment(linker, "/export:joySetCapture=C:\\Windows\\System32\\winmm.joySetCapture,@34")
#pragma comment(linker, "/export:joySetThreshold=C:\\Windows\\System32\\winmm.joySetThreshold,@35")
#pragma comment(linker, "/export:mci32Message=C:\\Windows\\System32\\winmm.mci32Message,@36")
#pragma comment(linker, "/export:mciDriverNotify=C:\\Windows\\System32\\winmm.mciDriverNotify,@37")
#pragma comment(linker, "/export:mciDriverYield=C:\\Windows\\System32\\winmm.mciDriverYield,@38")
#pragma comment(linker, "/export:mciExecute=C:\\Windows\\System32\\winmm.mciExecute,@3")
#pragma comment(linker, "/export:mciFreeCommandResource=C:\\Windows\\System32\\winmm.mciFreeCommandResource,@39")
#pragma comment(linker, "/export:mciGetCreatorTask=C:\\Windows\\System32\\winmm.mciGetCreatorTask,@40")
#pragma comment(linker, "/export:mciGetDeviceIDA=C:\\Windows\\System32\\winmm.mciGetDeviceIDA,@41")
#pragma comment(linker, "/export:mciGetDeviceIDFromElementIDA=C:\\Windows\\System32\\winmm.mciGetDeviceIDFromElementIDA,@42")
#pragma comment(linker, "/export:mciGetDeviceIDFromElementIDW=C:\\Windows\\System32\\winmm.mciGetDeviceIDFromElementIDW,@43")
#pragma comment(linker, "/export:mciGetDeviceIDW=C:\\Windows\\System32\\winmm.mciGetDeviceIDW,@44")
#pragma comment(linker, "/export:mciGetDriverData=C:\\Windows\\System32\\winmm.mciGetDriverData,@45")
#pragma comment(linker, "/export:mciGetErrorStringA=C:\\Windows\\System32\\winmm.mciGetErrorStringA,@46")
#pragma comment(linker, "/export:mciGetErrorStringW=C:\\Windows\\System32\\winmm.mciGetErrorStringW,@47")
#pragma comment(linker, "/export:mciGetYieldProc=C:\\Windows\\System32\\winmm.mciGetYieldProc,@48")
#pragma comment(linker, "/export:mciLoadCommandResource=C:\\Windows\\System32\\winmm.mciLoadCommandResource,@49")
#pragma comment(linker, "/export:mciSendCommandA=C:\\Windows\\System32\\winmm.mciSendCommandA,@50")
#pragma comment(linker, "/export:mciSendCommandW=C:\\Windows\\System32\\winmm.mciSendCommandW,@51")
#pragma comment(linker, "/export:mciSendStringA=C:\\Windows\\System32\\winmm.mciSendStringA,@52")
#pragma comment(linker, "/export:mciSendStringW=C:\\Windows\\System32\\winmm.mciSendStringW,@53")
#pragma comment(linker, "/export:mciSetDriverData=C:\\Windows\\System32\\winmm.mciSetDriverData,@54")
#pragma comment(linker, "/export:mciSetYieldProc=C:\\Windows\\System32\\winmm.mciSetYieldProc,@55")
#pragma comment(linker, "/export:mid32Message=C:\\Windows\\System32\\winmm.mid32Message,@56")
#pragma comment(linker, "/export:midiConnect=C:\\Windows\\System32\\winmm.midiConnect,@57")
#pragma comment(linker, "/export:midiDisconnect=C:\\Windows\\System32\\winmm.midiDisconnect,@58")
#pragma comment(linker, "/export:midiInAddBuffer=C:\\Windows\\System32\\winmm.midiInAddBuffer,@59")
#pragma comment(linker, "/export:midiInClose=C:\\Windows\\System32\\winmm.midiInClose,@60")
#pragma comment(linker, "/export:midiInGetDevCapsA=C:\\Windows\\System32\\winmm.midiInGetDevCapsA,@61")
#pragma comment(linker, "/export:midiInGetDevCapsW=C:\\Windows\\System32\\winmm.midiInGetDevCapsW,@62")
#pragma comment(linker, "/export:midiInGetErrorTextA=C:\\Windows\\System32\\winmm.midiInGetErrorTextA,@63")
#pragma comment(linker, "/export:midiInGetErrorTextW=C:\\Windows\\System32\\winmm.midiInGetErrorTextW,@64")
#pragma comment(linker, "/export:midiInGetID=C:\\Windows\\System32\\winmm.midiInGetID,@65")
#pragma comment(linker, "/export:midiInGetNumDevs=C:\\Windows\\System32\\winmm.midiInGetNumDevs,@66")
#pragma comment(linker, "/export:midiInMessage=C:\\Windows\\System32\\winmm.midiInMessage,@67")
#pragma comment(linker, "/export:midiInOpen=C:\\Windows\\System32\\winmm.midiInOpen,@68")
#pragma comment(linker, "/export:midiInPrepareHeader=C:\\Windows\\System32\\winmm.midiInPrepareHeader,@69")
#pragma comment(linker, "/export:midiInReset=C:\\Windows\\System32\\winmm.midiInReset,@70")
#pragma comment(linker, "/export:midiInStart=C:\\Windows\\System32\\winmm.midiInStart,@71")
#pragma comment(linker, "/export:midiInStop=C:\\Windows\\System32\\winmm.midiInStop,@72")
#pragma comment(linker, "/export:midiInUnprepareHeader=C:\\Windows\\System32\\winmm.midiInUnprepareHeader,@73")
#pragma comment(linker, "/export:midiOutCacheDrumPatches=C:\\Windows\\System32\\winmm.midiOutCacheDrumPatches,@74")
#pragma comment(linker, "/export:midiOutCachePatches=C:\\Windows\\System32\\winmm.midiOutCachePatches,@75")
#pragma comment(linker, "/export:midiOutClose=C:\\Windows\\System32\\winmm.midiOutClose,@76")
#pragma comment(linker, "/export:midiOutGetDevCapsA=C:\\Windows\\System32\\winmm.midiOutGetDevCapsA,@77")
#pragma comment(linker, "/export:midiOutGetDevCapsW=C:\\Windows\\System32\\winmm.midiOutGetDevCapsW,@78")
#pragma comment(linker, "/export:midiOutGetErrorTextA=C:\\Windows\\System32\\winmm.midiOutGetErrorTextA,@79")
#pragma comment(linker, "/export:midiOutGetErrorTextW=C:\\Windows\\System32\\winmm.midiOutGetErrorTextW,@80")
#pragma comment(linker, "/export:midiOutGetID=C:\\Windows\\System32\\winmm.midiOutGetID,@81")
#pragma comment(linker, "/export:midiOutGetNumDevs=C:\\Windows\\System32\\winmm.midiOutGetNumDevs,@82")
#pragma comment(linker, "/export:midiOutGetVolume=C:\\Windows\\System32\\winmm.midiOutGetVolume,@83")
#pragma comment(linker, "/export:midiOutLongMsg=C:\\Windows\\System32\\winmm.midiOutLongMsg,@84")
#pragma comment(linker, "/export:midiOutMessage=C:\\Windows\\System32\\winmm.midiOutMessage,@85")
#pragma comment(linker, "/export:midiOutOpen=C:\\Windows\\System32\\winmm.midiOutOpen,@86")
#pragma comment(linker, "/export:midiOutPrepareHeader=C:\\Windows\\System32\\winmm.midiOutPrepareHeader,@87")
#pragma comment(linker, "/export:midiOutReset=C:\\Windows\\System32\\winmm.midiOutReset,@88")
#pragma comment(linker, "/export:midiOutSetVolume=C:\\Windows\\System32\\winmm.midiOutSetVolume,@89")
#pragma comment(linker, "/export:midiOutShortMsg=C:\\Windows\\System32\\winmm.midiOutShortMsg,@90")
#pragma comment(linker, "/export:midiOutUnprepareHeader=C:\\Windows\\System32\\winmm.midiOutUnprepareHeader,@91")
#pragma comment(linker, "/export:midiStreamClose=C:\\Windows\\System32\\winmm.midiStreamClose,@92")
#pragma comment(linker, "/export:midiStreamOpen=C:\\Windows\\System32\\winmm.midiStreamOpen,@93")
#pragma comment(linker, "/export:midiStreamOut=C:\\Windows\\System32\\winmm.midiStreamOut,@94")
#pragma comment(linker, "/export:midiStreamPause=C:\\Windows\\System32\\winmm.midiStreamPause,@95")
#pragma comment(linker, "/export:midiStreamPosition=C:\\Windows\\System32\\winmm.midiStreamPosition,@96")
#pragma comment(linker, "/export:midiStreamProperty=C:\\Windows\\System32\\winmm.midiStreamProperty,@97")
#pragma comment(linker, "/export:midiStreamRestart=C:\\Windows\\System32\\winmm.midiStreamRestart,@98")
#pragma comment(linker, "/export:midiStreamStop=C:\\Windows\\System32\\winmm.midiStreamStop,@99")
#pragma comment(linker, "/export:mixerClose=C:\\Windows\\System32\\winmm.mixerClose,@100")
#pragma comment(linker, "/export:mixerGetControlDetailsA=C:\\Windows\\System32\\winmm.mixerGetControlDetailsA,@101")
#pragma comment(linker, "/export:mixerGetControlDetailsW=C:\\Windows\\System32\\winmm.mixerGetControlDetailsW,@102")
#pragma comment(linker, "/export:mixerGetDevCapsA=C:\\Windows\\System32\\winmm.mixerGetDevCapsA,@103")
#pragma comment(linker, "/export:mixerGetDevCapsW=C:\\Windows\\System32\\winmm.mixerGetDevCapsW,@104")
#pragma comment(linker, "/export:mixerGetID=C:\\Windows\\System32\\winmm.mixerGetID,@105")
#pragma comment(linker, "/export:mixerGetLineControlsA=C:\\Windows\\System32\\winmm.mixerGetLineControlsA,@106")
#pragma comment(linker, "/export:mixerGetLineControlsW=C:\\Windows\\System32\\winmm.mixerGetLineControlsW,@107")
#pragma comment(linker, "/export:mixerGetLineInfoA=C:\\Windows\\System32\\winmm.mixerGetLineInfoA,@108")
#pragma comment(linker, "/export:mixerGetLineInfoW=C:\\Windows\\System32\\winmm.mixerGetLineInfoW,@109")
#pragma comment(linker, "/export:mixerGetNumDevs=C:\\Windows\\System32\\winmm.mixerGetNumDevs,@110")
#pragma comment(linker, "/export:mixerMessage=C:\\Windows\\System32\\winmm.mixerMessage,@111")
#pragma comment(linker, "/export:mixerOpen=C:\\Windows\\System32\\winmm.mixerOpen,@112")
#pragma comment(linker, "/export:mixerSetControlDetails=C:\\Windows\\System32\\winmm.mixerSetControlDetails,@113")
#pragma comment(linker, "/export:mmDrvInstall=C:\\Windows\\System32\\winmm.mmDrvInstall,@114")
#pragma comment(linker, "/export:mmGetCurrentTask=C:\\Windows\\System32\\winmm.mmGetCurrentTask,@115")
#pragma comment(linker, "/export:mmTaskBlock=C:\\Windows\\System32\\winmm.mmTaskBlock,@116")
#pragma comment(linker, "/export:mmTaskCreate=C:\\Windows\\System32\\winmm.mmTaskCreate,@117")
#pragma comment(linker, "/export:mmTaskSignal=C:\\Windows\\System32\\winmm.mmTaskSignal,@118")
#pragma comment(linker, "/export:mmTaskYield=C:\\Windows\\System32\\winmm.mmTaskYield,@119")
#pragma comment(linker, "/export:mmioAdvance=C:\\Windows\\System32\\winmm.mmioAdvance,@120")
#pragma comment(linker, "/export:mmioAscend=C:\\Windows\\System32\\winmm.mmioAscend,@121")
#pragma comment(linker, "/export:mmioClose=C:\\Windows\\System32\\winmm.mmioClose,@122")
#pragma comment(linker, "/export:mmioCreateChunk=C:\\Windows\\System32\\winmm.mmioCreateChunk,@123")
#pragma comment(linker, "/export:mmioDescend=C:\\Windows\\System32\\winmm.mmioDescend,@124")
#pragma comment(linker, "/export:mmioFlush=C:\\Windows\\System32\\winmm.mmioFlush,@125")
#pragma comment(linker, "/export:mmioGetInfo=C:\\Windows\\System32\\winmm.mmioGetInfo,@126")
#pragma comment(linker, "/export:mmioInstallIOProcA=C:\\Windows\\System32\\winmm.mmioInstallIOProcA,@127")
#pragma comment(linker, "/export:mmioInstallIOProcW=C:\\Windows\\System32\\winmm.mmioInstallIOProcW,@128")
#pragma comment(linker, "/export:mmioOpenA=C:\\Windows\\System32\\winmm.mmioOpenA,@129")
#pragma comment(linker, "/export:mmioOpenW=C:\\Windows\\System32\\winmm.mmioOpenW,@130")
#pragma comment(linker, "/export:mmioRead=C:\\Windows\\System32\\winmm.mmioRead,@131")
#pragma comment(linker, "/export:mmioRenameA=C:\\Windows\\System32\\winmm.mmioRenameA,@132")
#pragma comment(linker, "/export:mmioRenameW=C:\\Windows\\System32\\winmm.mmioRenameW,@133")
#pragma comment(linker, "/export:mmioSeek=C:\\Windows\\System32\\winmm.mmioSeek,@134")
#pragma comment(linker, "/export:mmioSendMessage=C:\\Windows\\System32\\winmm.mmioSendMessage,@135")
#pragma comment(linker, "/export:mmioSetBuffer=C:\\Windows\\System32\\winmm.mmioSetBuffer,@136")
#pragma comment(linker, "/export:mmioSetInfo=C:\\Windows\\System32\\winmm.mmioSetInfo,@137")
#pragma comment(linker, "/export:mmioStringToFOURCCA=C:\\Windows\\System32\\winmm.mmioStringToFOURCCA,@138")
#pragma comment(linker, "/export:mmioStringToFOURCCW=C:\\Windows\\System32\\winmm.mmioStringToFOURCCW,@139")
#pragma comment(linker, "/export:mmioWrite=C:\\Windows\\System32\\winmm.mmioWrite,@140")
#pragma comment(linker, "/export:mmsystemGetVersion=C:\\Windows\\System32\\winmm.mmsystemGetVersion,@141")
#pragma comment(linker, "/export:mod32Message=C:\\Windows\\System32\\winmm.mod32Message,@142")
#pragma comment(linker, "/export:mxd32Message=C:\\Windows\\System32\\winmm.mxd32Message,@143")
#pragma comment(linker, "/export:sndPlaySoundA=C:\\Windows\\System32\\winmm.sndPlaySoundA,@144")
#pragma comment(linker, "/export:sndPlaySoundW=C:\\Windows\\System32\\winmm.sndPlaySoundW,@145")
#pragma comment(linker, "/export:tid32Message=C:\\Windows\\System32\\winmm.tid32Message,@146")
#pragma comment(linker, "/export:timeBeginPeriod=C:\\Windows\\System32\\winmm.timeBeginPeriod,@147")
#pragma comment(linker, "/export:timeEndPeriod=C:\\Windows\\System32\\winmm.timeEndPeriod,@148")
#pragma comment(linker, "/export:timeGetDevCaps=C:\\Windows\\System32\\winmm.timeGetDevCaps,@149")
#pragma comment(linker, "/export:timeGetSystemTime=C:\\Windows\\System32\\winmm.timeGetSystemTime,@150")
#pragma comment(linker, "/export:timeGetTime=C:\\Windows\\System32\\winmm.timeGetTime,@151")
#pragma comment(linker, "/export:timeKillEvent=C:\\Windows\\System32\\winmm.timeKillEvent,@152")
#pragma comment(linker, "/export:timeSetEvent=C:\\Windows\\System32\\winmm.timeSetEvent,@153")
#pragma comment(linker, "/export:waveInAddBuffer=C:\\Windows\\System32\\winmm.waveInAddBuffer,@154")
#pragma comment(linker, "/export:waveInClose=C:\\Windows\\System32\\winmm.waveInClose,@155")
#pragma comment(linker, "/export:waveInGetDevCapsA=C:\\Windows\\System32\\winmm.waveInGetDevCapsA,@156")
#pragma comment(linker, "/export:waveInGetDevCapsW=C:\\Windows\\System32\\winmm.waveInGetDevCapsW,@157")
#pragma comment(linker, "/export:waveInGetErrorTextA=C:\\Windows\\System32\\winmm.waveInGetErrorTextA,@158")
#pragma comment(linker, "/export:waveInGetErrorTextW=C:\\Windows\\System32\\winmm.waveInGetErrorTextW,@159")
#pragma comment(linker, "/export:waveInGetID=C:\\Windows\\System32\\winmm.waveInGetID,@160")
#pragma comment(linker, "/export:waveInGetNumDevs=C:\\Windows\\System32\\winmm.waveInGetNumDevs,@161")
#pragma comment(linker, "/export:waveInGetPosition=C:\\Windows\\System32\\winmm.waveInGetPosition,@162")
#pragma comment(linker, "/export:waveInMessage=C:\\Windows\\System32\\winmm.waveInMessage,@163")
#pragma comment(linker, "/export:waveInOpen=C:\\Windows\\System32\\winmm.waveInOpen,@164")
#pragma comment(linker, "/export:waveInPrepareHeader=C:\\Windows\\System32\\winmm.waveInPrepareHeader,@165")
#pragma comment(linker, "/export:waveInReset=C:\\Windows\\System32\\winmm.waveInReset,@166")
#pragma comment(linker, "/export:waveInStart=C:\\Windows\\System32\\winmm.waveInStart,@167")
#pragma comment(linker, "/export:waveInStop=C:\\Windows\\System32\\winmm.waveInStop,@168")
#pragma comment(linker, "/export:waveInUnprepareHeader=C:\\Windows\\System32\\winmm.waveInUnprepareHeader,@169")
#pragma comment(linker, "/export:waveOutBreakLoop=C:\\Windows\\System32\\winmm.waveOutBreakLoop,@170")
#pragma comment(linker, "/export:waveOutClose=C:\\Windows\\System32\\winmm.waveOutClose,@171")
#pragma comment(linker, "/export:waveOutGetDevCapsA=C:\\Windows\\System32\\winmm.waveOutGetDevCapsA,@172")
#pragma comment(linker, "/export:waveOutGetDevCapsW=C:\\Windows\\System32\\winmm.waveOutGetDevCapsW,@173")
#pragma comment(linker, "/export:waveOutGetErrorTextA=C:\\Windows\\System32\\winmm.waveOutGetErrorTextA,@174")
#pragma comment(linker, "/export:waveOutGetErrorTextW=C:\\Windows\\System32\\winmm.waveOutGetErrorTextW,@175")
#pragma comment(linker, "/export:waveOutGetID=C:\\Windows\\System32\\winmm.waveOutGetID,@176")
#pragma comment(linker, "/export:waveOutGetNumDevs=C:\\Windows\\System32\\winmm.waveOutGetNumDevs,@177")
#pragma comment(linker, "/export:waveOutGetPitch=C:\\Windows\\System32\\winmm.waveOutGetPitch,@178")
#pragma comment(linker, "/export:waveOutGetPlaybackRate=C:\\Windows\\System32\\winmm.waveOutGetPlaybackRate,@179")
#pragma comment(linker, "/export:waveOutGetPosition=C:\\Windows\\System32\\winmm.waveOutGetPosition,@180")
#pragma comment(linker, "/export:waveOutGetVolume=C:\\Windows\\System32\\winmm.waveOutGetVolume,@181")
#pragma comment(linker, "/export:waveOutMessage=C:\\Windows\\System32\\winmm.waveOutMessage,@182")
#pragma comment(linker, "/export:waveOutOpen=C:\\Windows\\System32\\winmm.waveOutOpen,@183")
#pragma comment(linker, "/export:waveOutPause=C:\\Windows\\System32\\winmm.waveOutPause,@184")
#pragma comment(linker, "/export:waveOutPrepareHeader=C:\\Windows\\System32\\winmm.waveOutPrepareHeader,@185")
#pragma comment(linker, "/export:waveOutReset=C:\\Windows\\System32\\winmm.waveOutReset,@186")
#pragma comment(linker, "/export:waveOutRestart=C:\\Windows\\System32\\winmm.waveOutRestart,@187")
#pragma comment(linker, "/export:waveOutSetPitch=C:\\Windows\\System32\\winmm.waveOutSetPitch,@188")
#pragma comment(linker, "/export:waveOutSetPlaybackRate=C:\\Windows\\System32\\winmm.waveOutSetPlaybackRate,@189")
#pragma comment(linker, "/export:waveOutSetVolume=C:\\Windows\\System32\\winmm.waveOutSetVolume,@190")
#pragma comment(linker, "/export:waveOutUnprepareHeader=C:\\Windows\\System32\\winmm.waveOutUnprepareHeader,@191")
#pragma comment(linker, "/export:waveOutWrite=C:\\Windows\\System32\\winmm.waveOutWrite,@192")
#pragma comment(linker, "/export:wid32Message=C:\\Windows\\System32\\winmm.wid32Message,@193")
#pragma comment(linker, "/export:wod32Message=C:\\Windows\\System32\\winmm.wod32Message,@194")
#pragma comment(linker, "/export:REAL_2=C:\\Windows\\System32\\winmm.#2,@2,NONAME")

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved) {
    if (fdwReason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(hinstDLL);
        MapSelectionFix::Logger::Initialize();
        MapSelectionFix::Logger::Log("[Main] DLL Loading...");
        MapSelectionFix::MapFix::Initialize();
        MapSelectionFix::LuaInterop::Initialize();
        if (kEnableNetTune) {
            MapSelectionFix::NetTune::Initialize();
            MapSelectionFix::Logger::Log("[Main] NetTune enabled");
        } else {
            MapSelectionFix::Logger::Log("[Main] NetTune disabled (SocketOptimizer-only mode)");
        }
        MapSelectionFix::SocketOptimizer::Initialize();
        MapSelectionFix::Logger::Log("[Main] DLL Loaded Successfully");
    } else if (fdwReason == DLL_PROCESS_DETACH) {
        MapSelectionFix::Logger::Log("[Main] Unloading DLL...");
        MapSelectionFix::SocketOptimizer::Shutdown();
        if (kEnableNetTune) {
            MapSelectionFix::NetTune::Shutdown();
        }
        MapSelectionFix::LuaInterop::Shutdown();
        MapSelectionFix::MapFix::Shutdown();
    }
    return TRUE;
}
